// Date: 3/8/2014 4:01:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package client.sudwood.mysticadditions.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOreRift extends ModelMysticBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
  
  public ModelOreRift()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 1, 16);
      Shape1.setRotationPoint(-8F, 23F, -8F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 1, 16);
      Shape2.setRotationPoint(7F, 23F, -8F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 35, 0);
      Shape3.addBox(0F, 0F, 0F, 14, 1, 1);
      Shape3.setRotationPoint(-7F, 23F, -8F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 34, 0);
      Shape4.addBox(0F, 0F, 0F, 14, 1, 1);
      Shape4.setRotationPoint(-7F, 23F, 7F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 18);
      Shape5.addBox(0F, 0F, 0F, 1, 11, 1);
      Shape5.setRotationPoint(-8F, 12F, -8F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 18);
      Shape6.addBox(0F, 0F, 0F, 1, 11, 1);
      Shape6.setRotationPoint(-8F, 12F, 7F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 18);
      Shape7.addBox(0F, 0F, 0F, 1, 11, 1);
      Shape7.setRotationPoint(7F, 12F, -8F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 18);
      Shape8.addBox(0F, 0F, 0F, 1, 11, 1);
      Shape8.setRotationPoint(7F, 12F, 7F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 34, 3);
      Shape9.addBox(0F, 0F, 0F, 14, 1, 1);
      Shape9.setRotationPoint(-7F, 12F, 7F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 34, 3);
      Shape10.addBox(0F, 0F, 0F, 14, 1, 1);
      Shape10.setRotationPoint(-7F, 12F, -8F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 5, 17);
      Shape11.addBox(0F, 0F, 0F, 1, 1, 14);
      Shape11.setRotationPoint(-8F, 12F, -7F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 5, 17);
      Shape12.addBox(0F, 0F, 0F, 1, 1, 14);
      Shape12.setRotationPoint(7F, 12F, -7F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      //first of drillshape
      Shape13 = new ModelRenderer(this, 36, 7);
      Shape13.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape13.setRotationPoint(0.5F, 21.5F, 0.5F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      
      Shape14 = new ModelRenderer(this, 36, 7);
      Shape14.addBox(-3.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape14.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      
      Shape15 = new ModelRenderer(this, 36, 7);
      Shape15.addBox(2.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape15.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      
      Shape16 = new ModelRenderer(this, 36, 7);
      Shape16.addBox(-0.5F, -0.5F, 2.5F, 1, 1, 1);
      Shape16.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      
      Shape17 = new ModelRenderer(this, 36, 7);
      Shape17.addBox(-0.5F, -0.5F, -3.5F, 1, 1, 1);
      Shape17.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      
      Shape18 = new ModelRenderer(this, 36, 7);
      Shape18.addBox(1.5F, -0.5F, 1.5F, 1, 1, 1);
      Shape18.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      
      Shape19 = new ModelRenderer(this, 36, 7);
      Shape19.addBox(-2.5F, -0.5F, -2.5F, 1, 1, 1);
      Shape19.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      
      Shape20 = new ModelRenderer(this, 36, 7);
      Shape20.addBox(-2.5F, -0.5F, 1.5F, 1, 1, 1);
      Shape20.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      
      Shape21 = new ModelRenderer(this, 36, 7);
      Shape21.addBox(1.5F, -0.5F, -2.5F, 1, 1, 1);
      Shape21.setRotationPoint(0.5F, 19.5F, 0.5F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      
      Shape22 = new ModelRenderer(this, 36, 7);
      Shape22.addBox(4.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape22.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      
      Shape23 = new ModelRenderer(this, 36, 7);
      Shape23.addBox(-0.5F, -0.5F, 4.5F, 1, 1, 1);
      Shape23.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      
      Shape24 = new ModelRenderer(this, 36, 7);
      Shape24.addBox(2F, -0.5F, 3.5F, 1, 1, 1);
      Shape24.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape24.setTextureSize(64, 32);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      
      Shape25 = new ModelRenderer(this, 36, 7);
      Shape25.addBox(-0.5F, -0.5F, -5.5F, 1, 1, 1);
      Shape25.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape25.setTextureSize(64, 32);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      
      Shape26 = new ModelRenderer(this, 36, 7);
      Shape26.addBox(-5.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape26.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape26.setTextureSize(64, 32);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      
      Shape27 = new ModelRenderer(this, 36, 7);
      Shape27.addBox(3.5F, -0.5F, 2F, 1, 1, 1);
      Shape27.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape27.setTextureSize(64, 32);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
      
      Shape28 = new ModelRenderer(this, 36, 7);
      Shape28.addBox(-3F, -0.5F, 3.5F, 1, 1, 1);
      Shape28.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape28.setTextureSize(64, 32);
      Shape28.mirror = true;
      setRotation(Shape28, 0F, 0F, 0F);
      
      Shape29 = new ModelRenderer(this, 36, 7);
      Shape29.addBox(-4.5F, -0.5F, 2F, 1, 1, 1);
      Shape29.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape29.setTextureSize(64, 32);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 0F, 0F);
      
      Shape30 = new ModelRenderer(this, 36, 7);
      Shape30.addBox(2F, -0.5F, -4.5F, 1, 1, 1);
      Shape30.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape30.setTextureSize(64, 32);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0F);
      
      Shape31 = new ModelRenderer(this, 36, 7);
      Shape31.addBox(3.5F, -0.5F, -3F, 1, 1, 1);
      Shape31.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape31.setTextureSize(64, 32);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      
      Shape32 = new ModelRenderer(this, 36, 7);
      Shape32.addBox(-4.5F, -0.5F, -3F, 1, 1, 1);
      Shape32.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape32.setTextureSize(64, 32);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0F);
      
      Shape33 = new ModelRenderer(this, 36, 7);
      Shape33.addBox(-3F, -0.5F, -4.5F, 1, 1, 1);
      Shape33.setRotationPoint(0.5F, 17.5F, 0.5F);
      Shape33.setTextureSize(64, 32);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
  }
  
  public void render(float f5)
  {
	  	Shape1.render(f5);
	    Shape2.render(f5);
	    Shape3.render(f5);
	    Shape4.render(f5);
	    Shape5.render(f5);
	    Shape6.render(f5);
	    Shape7.render(f5);
	    Shape8.render(f5);
	    Shape9.render(f5);
	    Shape10.render(f5);
	    Shape11.render(f5);
	    Shape12.render(f5);
	    Shape13.render(f5);
	    Shape14.render(f5);
	    Shape15.render(f5);
	    Shape16.render(f5);
	    Shape17.render(f5);
	    Shape18.render(f5);
	    Shape19.render(f5);
	    Shape20.render(f5);
	    Shape21.render(f5);
	    Shape22.render(f5);
	    Shape23.render(f5);
	    Shape24.render(f5);
	    Shape25.render(f5);
	    Shape26.render(f5);
	    Shape27.render(f5);
	    Shape28.render(f5);
	    Shape29.render(f5);
	    Shape30.render(f5);
	    Shape31.render(f5);
	    Shape32.render(f5);
	    Shape33.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  public void setSpinAngle(float yAngle)
  {
	  Shape13.rotateAngleY = yAngle;
	  Shape14.rotateAngleY = yAngle;
	  Shape15.rotateAngleY = yAngle;
	  Shape16.rotateAngleY = yAngle;
	  Shape17.rotateAngleY = yAngle;
	  Shape18.rotateAngleY = yAngle;
	  Shape19.rotateAngleY = yAngle;
	  Shape20.rotateAngleY = yAngle;
	  Shape21.rotateAngleY = yAngle;
	  Shape22.rotateAngleY = yAngle;
	  Shape23.rotateAngleY = yAngle;
	  Shape24.rotateAngleY = yAngle;
	  Shape25.rotateAngleY = yAngle;
	  Shape26.rotateAngleY = yAngle;
	  Shape27.rotateAngleY = yAngle;
	  Shape28.rotateAngleY = yAngle;
	  Shape29.rotateAngleY = yAngle;
	  Shape30.rotateAngleY = yAngle;
	  Shape31.rotateAngleY = yAngle;
	  Shape32.rotateAngleY = yAngle;
	  Shape33.rotateAngleY = yAngle;
  }

}
