// Date: 2/17/2013 9:48:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package client.sudwood.mysticadditions.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnergyBall extends ModelMysticBase
{
  //fields
    ModelRenderer CenterofSphere;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer LastofSphere;
  
  public ModelEnergyBall()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      CenterofSphere = new ModelRenderer(this, 0, 0);
      CenterofSphere.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      CenterofSphere.setRotationPoint(0F, 17.5F, 0F);
      CenterofSphere.setTextureSize(64, 32);
      CenterofSphere.mirror = true;
      setRotation(CenterofSphere, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 0);
      Shape11.addBox(3.5F, -0.5F, 3.5F, 1, 1, 1);
      Shape11.setRotationPoint(0F, 17.5F, 0F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 0);
      Shape12.addBox(-3.5F, -0.5F, -4.5F, 1, 1, 1);
      Shape12.setRotationPoint(0F, 17.5F, 0F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 0, 0);
      Shape13.addBox(3.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape13.setRotationPoint(0F, 17.5F, 0F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 0);
      Shape14.addBox(-0.5F, -0.5F, 3.5F, 1, 1, 1);
      Shape14.setRotationPoint(0F, 17.5F, 0F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 0);
      Shape15.addBox(3.5F, -0.5F, -4.5F, 1, 1, 1);
      Shape15.setRotationPoint(0F, 17.5F, 0F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 0);
      Shape16.addBox(-0.5F, -0.5F, -4.5F, 1, 1, 1);
      Shape16.setRotationPoint(0F, 17.5F, 0F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 0);
      Shape17.addBox(-3.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape17.setRotationPoint(0F, 17.5F, 0F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 0, 0);
      Shape18.addBox(-3.5F, -0.5F, 3.5F, 1, 1, 1);
      Shape18.setRotationPoint(0F, 17.5F, 0F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 0, 0);
      Shape19.addBox(1.5F, -0.5F, 1.5F, 1, 1, 1);
      Shape19.setRotationPoint(0F, 15.5F, 0F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 0, 0);
      Shape20.addBox(-2.5F, -0.5F, 1.5F, 1, 1, 1);
      Shape20.setRotationPoint(0F, 15.5F, 0F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 0, 0);
      Shape21.addBox(-2.5F, -0.5F, -2.5F, 1, 1, 1);
      Shape21.setRotationPoint(0F, 15.5F, 0F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 0, 0);
      Shape22.addBox(1.5F, -0.5F, -2.5F, 1, 1, 1);
      Shape22.setRotationPoint(0F, 15.5F, 0F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 0, 0);
      Shape23.addBox(-0.5F, -4F, -0.5F, 1, 1, 1);
      Shape23.setRotationPoint(0F, 17.5F, 0F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 0, 0);
      Shape24.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      Shape24.setRotationPoint(0F, 17.5F, 0F);
      Shape24.setTextureSize(64, 32);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 0, 0);
      Shape25.addBox(1.5F, -0.5F, 1.5F, 1, 1, 1);
      Shape25.setRotationPoint(0F, 19.5F, 0F);
      Shape25.setTextureSize(64, 32);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 0, 0);
      Shape26.addBox(-2.5F, -0.5F, 1.5F, 1, 1, 1);
      Shape26.setRotationPoint(0F, 19.5F, 0F);
      Shape26.setTextureSize(64, 32);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 0, 0);
      Shape27.addBox(1.5F, -0.5F, -2.5F, 1, 1, 1);
      Shape27.setRotationPoint(0F, 19.5F, 0F);
      Shape27.setTextureSize(64, 32);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 0, 0);
      Shape28.addBox(-2.5F, -0.5F, -2.5F, 1, 1, 1);
      Shape28.setRotationPoint(0F, 19.5F, 0F);
      Shape28.setTextureSize(64, 32);
      Shape28.mirror = true;
      setRotation(Shape28, 0F, 0F, 0F);
      LastofSphere = new ModelRenderer(this, 0, 0);
      LastofSphere.addBox(-0.5F, 2.5F, -0.5F, 1, 1, 1);
      LastofSphere.setRotationPoint(0F, 17.5F, 0F);
      LastofSphere.setTextureSize(64, 32);
      LastofSphere.mirror = true;
      setRotation(LastofSphere, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    CenterofSphere.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    LastofSphere.render(f5);
  }
  public void render(float f5)
  {
	  CenterofSphere.render(f5);
	    Shape11.render(f5);
	    Shape12.render(f5);
	    Shape13.render(f5);
	    Shape14.render(f5);
	    Shape15.render(f5);
	    Shape16.render(f5);
	    Shape17.render(f5);
	    Shape18.render(f5);
	    Shape19.render(f5);
	    Shape20.render(f5);
	    Shape21.render(f5);
	    Shape22.render(f5);
	    Shape23.render(f5);
	    Shape24.render(f5);
	    Shape25.render(f5);
	    Shape26.render(f5);
	    Shape27.render(f5);
	    Shape28.render(f5);
	    LastofSphere.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  public void setRotationAngleSpin(ModelRenderer model, float angleX, float angleY, float angleZ)
  {
	  model.rotateAngleX = angleX;
	  model.rotateAngleY = angleY;
	  model.rotateAngleZ = angleZ;
  }
  
  
  public void spinCenter(float angleX, float angleY, float angleZ)
  {
	  this.setRotationAngleSpin(CenterofSphere, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape11, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape12, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape13, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape14, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape15, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape16, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape17, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape18, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape19, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape20, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape21, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape22, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape23, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape24, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape25, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape26, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(Shape27, angleX, angleY, angleZ);
	  this.setRotationAngleSpin(Shape28, -angleX, -angleY, -angleZ);
	  this.setRotationAngleSpin(LastofSphere, angleX, angleY, angleZ);
  }

}
